version: "3.8"

services:
  backend:
    build: ./backend
    container_name: smart-backend
    ports:
      - "8000:8000"
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
    restart: unless-stopped
