version: "3.8"

services:
  backend:
    build: ./backend
    container_name: smart-backend
    ports:
      - "8000:8000"
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - RUN_DATA_GENERATOR=false # Disable internal data generation for deployment
    restart: unless-stopped

  frontend:
    build: ./dashboard
    container_name: smart-frontend
    ports:
      - "3000:80" # Map host port 3000 to container's Nginx port 80
    depends_on:
      - backend # Ensure backend starts before frontend
    restart: unless-stopped
